### ISSUE TITLE
where are the names of the folders under species level dictated?

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/datastore-specifications#2]
I thought we had agreed on genetic (or genetics?) as the containing folder for gwas and qtl but it looks like v2 has them separate as gwas and qtl. The README for this repository says:
genetic.md = files under /genetic/

which makes me think it is supposed to be not separated, but maybe I am misinterpreting. In any case, we should have a clear place where official subfolder names are decreed. I don't know if Popes or Czars make such decisions, but I did just learn about https://en.wikipedia.org/wiki/Tsar_Cannon

**Comment by sammyjava** [comment]
Don't look at the datastore at Ames. It will be replaced by what I've built on shokin-mines. I've not done that yet. Many, many changes.

**Comment by sammyjava** [comment]
At the top of each spec in this repo. If not what you're thinking of, put what you're thinking of in this repo.

**Comment by adf-ncgr** [comment]
works for me. will be nice when we get the full set with at least a placeholder spec. What would you say to actually making folders in the repo that would be named correctly and would contain the relevant spec(s) for those folders? e.g. we would have annotations folder that would contain pathway-assignments.md and gene-family-assignments.md and (eventually) something for the rest of the annotations content? This seems to be a little easier to navigate to me and would mean you don't have to repeat yourself with respect to folder naming in cases where there are multiple specs for different file types.

**Comment by sammyjava** [comment]
Makes sense, I'll do it.

**Comment by cann0010** [comment]
I agree that this sounds like a good scheme. (Sorry not to have been more fully engaged lately; family visit the last week and a half has taken all my focus).

**Comment by adf-ncgr** [comment]
no worries, glad to have you back! (if indeed you are back)
