### ISSUE TITLE
RFC: split /genetic into /gwas and /qtl collections

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/datastore-specifications#29]
Currently /genetic contains both GWAS and QTL studies. This was originally motivated by wanting to accommodate _publications_ that contained both GWAS and QTL experiments. But we've moved away from a one-to-one correspondence between publications and collections.

Later, we decided to demark GWAS collections with .gwas. and QTL study collections with .qtl. effectively splitting them apart within /genetic/. That is the current state of the DS: all GWAS are under /genetic/x.gwas.x and all QTL are under /genetic/x.gen.x

Note: This makes our /genetic/ collections inconsistent with the rest of the DS, in that we have both .gwas. and .gen. collections under /genetic/ while all other collection directories have a single .abc. on the collections within them.

**Proposal**: let's make this clear with separate collection directories and dropping /genetic/:

- /gwas/ contains .gwas. collections which contain GWAS
- /qtl/ contains .qtl. collections which contain QTL studies

The GWAS update is trivial, just moving those directories to /gwas.

The QTL update is slightly less trivial, renaming the top directory to /qtl, renaming the collections to .qtl. and renaming all the files to .qtl. But that's why we have scripts which I'll be happy to implement (using `git mv` so we deal with that aspect of things).

The _specified_ DS file structure under species will then look like:

- about_this_collection
- annotations
- diversity
- expression
- genomes
- gwas
- maps
- markers
- qtl
- synteny

(ignoring as-yet non-specified directories which appear in various places).

This may make @svengato 's life slightly easier, but perhaps not even noticeable. My QTL and GWAS loaders are easy to separate out of my lis-genetic loader, as they're really independent loads, anyway.

**Comment by svengato** [comment]
> This may make @svengato <https://github.com/svengato> 's life slightly
> easier, but perhaps not even noticeable.


Right - the changes will be trivial.

**Comment by sammyjava** [comment]
I'll implement the rearrangement if we decide to do it. Sounds like that's a GO unless @adf-ncgr or @sdash-github or @ctcncgr have major objections. I said "RFC" not "RFO" expecting none. :)

**Comment by adf-ncgr** [comment]
no objections here

**Comment by sdash-github** [comment]
I am with the split into two for convenience.

**Comment by sammyjava** [comment]
Sounds like a quorum, I'll remove y'all from the assignees and add it to my tasks. Let me know if there's a desired delay for implementation, I'm in no great hurry.

**Comment by sdash-github** [comment]
I am not sure why there should be a delay unless one of us is doing some 
update or something similar. But that is up to the developer.

 From PeanutBase point of view, let us do it soon, as 1.)  an annual 
report is due and 2.) it will help in writing, in the new PB-Jekyll 
site, a page content that directs to PeanutMine and what to expect 
there. We are trying the new site to be minimally presentable by Sep-30.
