### ISSUE TITLE
RFC: Add counts matrix to expression sets

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/datastore-specifications#32]
We should add a file that contains the "raw" counts per sample per gene in addition to the TPM values, e.g.

`phavu.G19833.gnm1.ann1.expr.Negro_jamapa.ORourke_Iniguez_2014.counts.tsv.gz`

**Comment by el239** [comment]
I've added notes for this to the datastore-specifications page, qualifying it as an optional file.
