### ISSUE TITLE
mismatch between synteny spec and actual practice?

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/datastore-specifications#34]
While trying to cop the synteny spec for use in the genome_alignments context, I noticed that the spec doesn't include keys in the file names whereas they seem to be included in datastore files. e.g.: spec sez:
Example:
```
IT97K-499-35.gnm1.syn.W3NY
├── vigun.IT97K-499-35.gnm1.x.glyma.Wm82.gnm2.gff.gz
├── vigun.IT97K-499-35.gnm1.x.phavu.G19833.gnm1.gff.gz
├── vigun.IT97K-499-35.gnm1.x.vigan.Gyeongwon.gnm3.gff.gz
├── vigun.IT97K-499-35.gnm1.x.vigra.VC1973A.gnm6.gff.gz
└── vigun.IT97K-499-35.gnm1.x.vigun.IT97K-499-35.gnm1.gff.gz
```
while datastore has:
[adf@lis-stage /usr/local/www/data/v2/Vigna/unguiculata/synteny/IT97K-499-35.gnm1.syn.W3NY]$ ls
README.IT97K-499-35.gnm1.syn.W3NY.yml
vigun.IT97K-499-35.gnm1.x.glyma.Wm82.gnm2.W3NY.gff3.gz
vigun.IT97K-499-35.gnm1.x.phavu.G19833.gnm1.W3NY.gff3.gz
vigun.IT97K-499-35.gnm1.x.vigan.Gyeongwon.gnm3.W3NY.gff3.gz
vigun.IT97K-499-35.gnm1.x.vigra.VC1973A.gnm6.W3NY.gff3.gz
vigun.IT97K-499-35.gnm1.x.vigun.IT97K-499-35.gnm1.W3NY.gff3.gz

I'm guessing the latter is considered correct, but will defer to the keymasters.

**Comment by cann0010** [comment]
Yeah, I think "the latter is considered correct", following the general pattern that files include the key.

**Comment by sammyjava** [comment]
I updated the spec.
