### ISSUE TITLE
Current pangene spec requires scientific_name_abbrev not be required; I'd like to have it.

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/datastore-specifications#41]
I just want to put this out there before I change the required values for ALL READMEs in the datastore. Right now, the following are required across the board by all mine loaders: identifier, taxid, scientific_name_abbrev, synopsis, and description.

The pangene README does not have scientific_name_abbrev since we don't have one for a genus. So, by relaxing that requirement, I'll be allowing all the READMEs that *should* contain it to lack it (due to operator error, which is common).

**The alternative is to create a scientific_name_abbrev for genera**, just as we are using the taxid for genera. I'd prefer that.

Or, I can relax it in the core README code and make it required for every darned collection OTHER than pangenes. I'd really NOT like to do that!

Slightly related: The additional terms `annotations_main` and `annotations_extra` will be put into PangeneCollectionValidator. I presume that `annotations_main` is required and `annotations_extra` is not. Correct me if I'm wrong, @StevenCannon-USDA .

**Comment by sammyjava** [comment]
Also, there are a lot of files in those collections, but only hsh.tsv.gz and clust.tsv.gz are specified, so those are the only ones I'll check in PangeneCollectionValidator (other than the README). FYI.

**Comment by sammyjava** [comment]
And note that it doesn't really matter WHAT the genus scientific_name_abbreviation is, it could be aaaaa, bbbbb, ccccc for all I care. I'd just rather keep that as a required field across the board.

**Comment by adf-ncgr** [comment]
Hmm, I think it will be a little confusing to have it not actually match what we use as the prefix for the files in the collection. But I guess the issue with having e.g.
```
scientific_name: Glycine
scientific_name_abbrev: Glycine
```
is that it wouldn't validate according to the "gensp" pattern specified generally (unless we relax that, which probably isn't all that much different than making it optional). 
Not sure why the current schema has two pattern specifications, though? 
https://github.com/legumeinfo/datastore-specifications/blob/8af3e8ed1f51c93672febf8c9e49a8c3efcd80c6/readme.schema.json#L46

**Comment by sammyjava** [comment]
No, that's fine, actually. Yes, it makes sense to have it simply be the name of the Genus.

**Comment by adf-ncgr** [comment]
OK, I'm fine with it then.

**Comment by sammyjava** [comment]
Also, up to now I've required `publication_doi`, meaning I've put the LIS publication in for stuff we've cooked. But perhaps relaxing that requirement is reasonable, it should be obvious that the lack of a publication means we cooked it. Plus, the LIS publication doesn't actually say anything about a lot of stuff we've cooked.

**Comment by sammyjava** [comment]
Just a note: normally the collection does not include the gensp prefix. So I prepend it to the collection to get the filenames inside. Which throws this now, which I can deal with, but just pointing out this inconsistency. In principle, the collections under Phaseolus/GENUS/pangenes should not have a Phaseolus prefix for consistency with the other collections. (To be honest, the lack of gensp on collection dir names has been a PITA in a number of ways!)
```
Retrieving Phaseolus.pan1.X2PC in a tgt items database
[convertFile] ## INVALID: Required file Phaseolus.Phaseolus.pan1.X2PC.clust.tsv.gz is not present in Phaseolus.pan1.X2PC
[convertFile] ## INVALID: Required file Phaseolus.Phaseolus.pan1.X2PC.hsh.tsv.gz is not present in Phaseolus.pan1.X2PC
[convertFile] ## INVALID: Missing required files.
```

**Comment by adf-ncgr** [comment]
yeah, I think making publication_doi optional is sensible. It's weird to see the LIS publication cited in genomes that haven't been associated with publications but which we've picked up from phytozome, e.g. in https://data.legumeinfo.org/Phaseolus/vulgaris/genomes/UI111.gnm1.3VTM/README.UI111.gnm1.3VTM.yml
which I guess you must have post-processed to conform to the requirement. I don't consider this to really be something from our kitchen, even though the sous-chef may have been involved.

**Comment by adf-ncgr** [comment]
> Just a note: normally the collection does not include the gensp prefix.

I wouldn't mind adding gensp to the others, which might then obviate the need to have it explicitly in the READMEs. my A has felt the PITA you reference above. Of course, this would change a lot of URLs so probably not something to be done offhandedly.

**Comment by sammyjava** [comment]
>I think I'd like to add these two: pctl25_named_cds.fna.gz and pctl25_named_protein.faa.gz.
Fine with me, but normally I only validate stuff that I load into the mines - and it seems that you'd like me to load these into the mines. So, they're BioEntities (they have a sequence, but it's not located on a specific genome) like Protein or CDS (as opposed to CDSRegion, see discussion ages ago about that). What are they to be called? PanGeneExemplarCDS and PanGeneExemplarProtein? Kinda clunky. But happy to validate and load them.

**Comment by sammyjava** [comment]
Every object in a mine has a class name. Like Gene or Protein or Chromosome. I need to name the objects that hold these chunks of sequence if I load them.

I'm not sure we want to get into creating pseudo-genomes with pseudo-CDSes mapped to them (without introns, presumably). I think just storing the sequences, like we already do with proteins and CDSes, is what we want. We can certainly annotate which pseudo-chromosome they are associated with.

What do you mean by "an exemplar is used in a family/tree"? Are you talking about a new generation of gene families that use your pan-gene exemplar sequences as basis? If so, this seems rather developmental at this point and I think I'd stick with just loading the clust files if the FASTAs don't have a downstream use yet.

I don't see the connection between a pangene set and a current LIS gene family from the spec.

**Comment by StevenCannon-USDA** [comment]
"Every object in a mine has a class name" -- I see. In that case, PanGeneExemplarCDS seems as good a name as any.

"talking about a new generation of gene families that use your pan-gene exemplar sequences as basis?" - Yes. I am working on calculating new gene families now. I could proceed as before, just using a single selected annotation per species; but I think that using the pan-gene exemplars would have some advantages. They should generally be cleaner (no stop codons, few size outliers) and more complete.

"I don't see the connection between a pangene set and a current LIS gene family from the spec." - Right. Still conceptual/proposed. Which suggests that I should write up a RFO ... :-)

**Comment by adf-ncgr** [comment]
Why don't we plan to discuss this a bit in the next Wednesday group meeting? I am also not entirely sure what needs to be modeled in the mines for these, but it would be good to flesh out Steven's vision a bit more before we do that. FWIW, as Steven knows but maybe Sam doesn't I have some "developmental" stuff that is probably reasonably close to production for GCVs with pangenes and their "pseudo-genomes", see e.g. http://dev.lis.ncgr.org:50015/arachis_pan/gcv/gene;lis=Arachis.pan1.chr15_196300_pan32469
but whether these need counterparts in the mine other than the pangene set is not clear to me. Similarly, since the exemplar sequences are just selections from the set, it seems like we may not need to actually store them as separate entities, we could just indicate which sequence is the exemplar since that info is stored in the headers. Just my few cents, but I definitely think some further realtime discussion could be good before plunging into a remodel.

**Comment by sammyjava** [comment]
BTW, it's fairly boring, but I've loaded the phavu and cicer pangene sets into a dev MiniMine minimal build:

https://lupini.lis.ncgr.org/minimine/report.do?id=12098927
https://lupini.lis.ncgr.org/minimine/report.do?id=2158796

Note: I'm using collections Protein.panGeneSets and Gene.panGeneSets for the same reason as gene families: we may want to support multiple versions, right? (And we store Phytozome gene family assignments as well as LIS gene family assignments in that case.) But if we're committed to only ever having one pangene set per gene, I'll make that a reference instead.

**Comment by sammyjava** [comment]
Steven: this is a lovely artifact from publication_doi: "". My publication lookup routine didn't handle a blank DOI properly. :) Fixing the README. :)
```
minimine-dev=> select * from publication where id=12000002;
-[ RECORD 1 ]---+--------------------------------------------------------------------------------------------------------------------------------------------
intermine_year  | 2007
issue           | 18_suppl
id              | 12000002
title           | Circulating tumor cells expressing the insulin growth factor-1 receptor (IGF-1R): Method of detection, incidence and potential applications
pages           | 3507-3507
doi             | 10.1200/jco.2007.25.18_suppl.3507
volume          | 25
journal         | JCO
firstauthor     | de Bono, J. S.
intermine_month | 6
abstracttext    | 
pubmedid        | 
class           | org.intermine.model.bio.Publication
```

**Comment by adf-ncgr** [comment]
I was just wondering what the relevance of that reference was!

**Comment by StevenCannon-USDA** [comment]
Ha! How does two-quotes get turned into THAT?!

**Comment by sammyjava** [comment]
(I'll add DOI validation if publication_doi is present, seems like a good idea. Check for presence of at least one dot and slash should be a minimal requirement.)

**Comment by StevenCannon-USDA** [comment]
Seems to have been hashed out and addressed last year. Closing.
