### ISSUE TITLE
Gene_function readme needs a link to get_citations.pl

### ISSUE THREAD

**Issue by maxglycine** [legumeinfo/datastore-specifications#46]
I was reading the readme and it mentions get_citations.pl repeatedly, but does not say where to find it.  Either tell us where to find it or make the first reference a link to where it is.

**Comment by StevenCannon-USDA** [comment]
Good point. I have added a link (it is in scripts/ at the root level of the repository).

**Comment by adf-ncgr** [comment]
@StevenCannon-USDA are you sure you've added the script to the repo? I don't see it in /scripts (assuming I should be looking in this repo).

**Comment by StevenCannon-USDA** [comment]
@adf-ncgr It's actually over at the https://github.com/legumeinfo/gene-function-registry repository. There is a corresponding specification here, but the curation and review happens in the other registry. I'd like to review all of this and figure out how to reduce the likelihood of confusion.

**Comment by adf-ncgr** [comment]
Ah, thanks, I was indeed among the confused; looks like you've been making great progress on this effort! I'd be interested to get an overview of how things are being done and start planning how we can incorporate the info you've been collecting into some of our tools. Also wouldn't mind contributing to the curation effort a bit; perhaps by slowing working my way through the publications summarized here https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6961631/figure/fig2/ or wherever  else you think would be a good place for an aspiring curator with my background to start digging in...

**Comment by StevenCannon-USDA** [comment]
@adf-ncgr - sure, I'll be happy to give an overview, and you are very welcome to contribute! That nodulation review looks like an excellent source. For easy reference, if anyone else is following along:
Roy S, Liu W, Nandety RS, Crook A, Mysore KS, Pislariu CI, Frugoli J, Dickstein R, Udvardi MK. Celebrating 20 Years of Genetic Discoveries in Legume Nodulation and Symbiotic Nitrogen Fixation. Plant Cell. 2020 Jan;32(1):15-41. doi: 10.1105/tpc.19.00279. Epub 2019 Oct 24. PMID: 31649123; PMCID: PMC6961631.

**Comment by adf-ncgr** [comment]
sounds good, will look forward to an indoctrination soon!
