### ISSUE TITLE
Datastore-specification/protocols/gene_function 

### ISSUE THREAD

**Issue by maxglycine** [legumeinfo/datastore-specifications#47]
I note this sentence "Periodically as you work check in your changes (to your branch; you can do this without requesting review):"
I think a better flow would be to make the YAML documents locally, run it through the YAML checker and at the end of the work day transfer it to a new branch and then put in a PR for it.  If you did it like that there would be minimal chance that your branch would be behind as long as there is a quick review.

**Comment by StevenCannon-USDA** [comment]
Thanks; I agree. I have lightly edited the README. I'll plan to review and edit it more rigorously in a week or so.
