### ISSUE TITLE
Where do you get the validation program

### ISSUE THREAD

**Issue by maxglycine** [legumeinfo/datastore-specifications#48]
Where do you get the pajv "readme" validation program,  "pajv"  in the https://github.com/legumeinfo/datastore-specifications "readme" file.  It should be a link to the program @StevenCannon-USDA

**Comment by adf-ncgr** [comment]
https://www.npmjs.com/package/pajv#installation

**Comment by sammyjava** [comment]
But it's not used any more, **ajv** is. The README was out of date. I've updated it. The ajv script installation is shown at the top of the validate script, it's an NPM module.

**Comment by adf-ncgr** [comment]
Oh yeah, I guess https://github.com/legumeinfo/datastore-metadata/blob/main/.github/workflows/validate.yml should be considered normative for this (since it will be what gets run on the files when pushed up to the github)

**Comment by sammyjava** [comment]
Yeah I think we went to ajv when we (I?) discovered that we can use the ajv-formats config parameter.

**Comment by StevenCannon-USDA** [comment]
Closing this, as it looks like it was answered in February.
